![Ironhack logo](https://i.imgur.com/1QgrNNw.png)

# Lab | Numpy

## Introduction

An important ability of a data scientist/data engineer is to know where and how to find information that helps you to accomplish your work. In the exercise, you will both practice the Numpy features we discussed in the lesson and learn new features by looking up documentations and references. You will work on your own but remember the teaching staff is at your service whenever you encounter problems.

## Getting Started
There are a bunch of comments which instruct what you are supposed to do step by step. Follow the order of the instructions from top to bottom. Read each instruction carefully and provide your answer beneath it. You should also test your answers to make sure your responses are correct. If one of your responses is incorrect, you may not be able to proceed because later responses may depend upon previous responses.


## Resources

Some of the questions in the assignment are not covered in our lesson. You will learn how to efficiently look up the information on your own. Below are some resources you can find the information you need.

[Numpy User Guide](https://docs.scipy.org/doc/numpy/user/index.html)

[Numpy Reference](https://docs.scipy.org/doc/numpy/reference/)

[Google Search](https://www.google.com/search?q=how+to+use+numpy)



# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [2]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
print(np.__version__)

1.19.1


#### 3. Generate a 3x2x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

**Example of output**:
````python
[[[0.29932768, 0.85812686, 0.75266145, 0.09278988, 0.78358352],
  [0.13437453, 0.65695946, 0.82047594, 0.09764179, 0.52230096]],
 
 [[0.54248247, 0.06431281, 0.65902257, 0.92736679, 0.3302839 ],
  [0.86867236, 0.33960592, 0.62295821, 0.74563567, 0.24351584]],
 
 [[0.21276812, 0.06917533, 0.35106591, 0.82273425, 0.7910178 ],
  [0.37768961, 0.56107736, 0.99965953, 0.97615549, 0.2445537 ]]]
````

In [3]:
# Method 1
a = np.random.random((3,2,5))

In [4]:
# Method 2
from numpy import random
a = random.randint(100, size=(3,2,5))

In [12]:
# Method 3
a = np.array([[[1,2,3,4,5],[6,7,8,9,10]],[[11,12,13,14,15],[16,17,18,19,20]],[[21,22,23,24,25],[26,27,28,29,30]]])

#### 4. Print *a*.


In [11]:
# your code here
print(a)

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

Expected output:

````python
      [[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]]
````

In [14]:
# your code here
b = np.ones((5,2,3))

#### 6. Print *b*.


In [15]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [16]:
# your code here
a.size == b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [17]:
# your answer here
a.shape == b.shape

False

#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 3x2x5 array). Assign the reshaped array to variable *c*.

Expected output:

````python
      [[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]]
````

In [18]:
# your code here
c = b.reshape(3,2,5)
c.shape

(3, 2, 5)

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [19]:
# your code/answer here
d = a+c
d
#a.shape == c.shape

array([[[ 2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11.]],

       [[12., 13., 14., 15., 16.],
        [17., 18., 19., 20., 21.]],

       [[22., 23., 24., 25., 26.],
        [27., 28., 29., 30., 31.]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [20]:
# your code/answer here
print(a)
print(d)
#d == a+1

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]]
[[[ 2.  3.  4.  5.  6.]
  [ 7.  8.  9. 10. 11.]]

 [[12. 13. 14. 15. 16.]
  [17. 18. 19. 20. 21.]]

 [[22. 23. 24. 25. 26.]
  [27. 28. 29. 30. 31.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [21]:
# your code here
e = a*c
e

array([[[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]],

       [[11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.]],

       [[21., 22., 23., 24., 25.],
        [26., 27., 28., 29., 30.]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [0]:
# your code/answer here
#e == a
#c é uma array com apenas 1 e qualquer numero multiplicado por retornara ele mesmo

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [36]:
d = [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],

[[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],

[[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
 [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]

In [42]:
d[0][0][1]

1.67064465

In [37]:
# your code here
d_mean = np.mean(d)
d_max = np.max(d)
d_min = np.min(d) 
print(d_mean,d_max,d_min)

1.6175069086666667 1.97066381 1.00656599


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 3x2x5) as *d* using `np.empty`.


In [38]:
# your code here
f = np.empty([3,2,5])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [43]:
# your code here
for first in range (0,3):
    for second in range(0,2):
        for third in range (0,5):
            if d_mean>d[first][second][third]>d_min:
                f[first][second][third]=25
            elif d_max>d[first][second][third]>d_mean:
                f[first][second][third]=75
            elif d[first][second][third]==d_mean:
                f[first][second][third]=50
            elif d[first][second][third]==d_min:
                f[first][second][third]=0   
            elif d[first][second][third]==d_max:
                f[first][second][third]=100   

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
  [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981]],

[[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042],
  [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381]],

[[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
 [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
```

In [44]:
# your code here
print(f)

[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  75.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'B' 'E']]

 [['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [53]:
# your code here
fstr = np.array([[['a','a','a','a','a'],['a','a','a','a','a']],[['a','a','a','a','a'],['a','a','a','a','a']],[['a','a','a','a','a'],['a','a','a','a','a']]])
for first in range (0,3):
    for second in range (0,2):
        for third in range (0,5):
            if f[first][second][third]==0:
                fstr[first][second][third]='A'
            elif f[first][second][third]==25:
                fstr[first][second][third]='B'
            elif f[first][second][third]==50:
                fstr[first][second][third]='C'
            elif f[first][second][third]==75:
                fstr[first][second][third]='D'
            elif f[first][second][third]==100:
                fstr[first][second][third]='E'
                
                

In [54]:
fstr

array([[['D', 'D', 'D', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'B']],

       [['D', 'B', 'D', 'D', 'D'],
        ['B', 'B', 'B', 'B', 'E']],

       [['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'A', 'D', 'D']]], dtype='<U1')

## Additional Challenges for the Nerds

If you are way ahead of your classmates and willing to accept some tough challenges about Numpy, take one or several of the following Codewar *katas*. 	You need to already possess a good amount of knowledge in Python and statistics because you will need to write Python functions, do loops, write conditionals, and deal with matrices.

* [Insert dashes](https://www.codewars.com/kata/insert-dashes)
* [Thinkful - Logic Drills: Red and bumpy](https://www.codewars.com/kata/thinkful-logic-drills-red-and-bumpy)

Write a function insertDash(num)/InsertDash(int num) that will insert dashes ('-') between each two odd numbers in num. For example: if num is 454793 the output should be 4547-9-3. Don't count zero as an odd number.

Note that the number will always be non-negative (>= 0).

In [37]:
def insertDash(x):
    ans = str('')
    x = str(x)
    x = x.replace('',' ')
    x = x.split(sep=' ')

    for i in range (1,len(x)-2):
        if int(x[i])%2!=0 and int(x[i+1])%2!=0:
            x[i] = x[i]+'-'
        

    for i in x:
        ans = ans + i
    return ans    
    

In [38]:
insertDash(454793)

'4547-9-3'

You're playing a game with a friend involving a bag of marbles. In the bag are ten marbles:

1 smooth red marble
4 bumpy red marbles
2 bumpy yellow marbles
1 smooth yellow marble
1 bumpy green marble
1 smooth green marble
You can see that the probability of picking a smooth red marble from the bag is 1 / 10 or 0.10 and the probability of picking a bumpy yellow marble is 2 / 10 or 0.20.

The game works like this: your friend puts her hand in the bag, chooses a marble (without looking at it) and tells you whether it's bumpy or smooth. Then you have to guess which color it is before she pulls it out and reveals whether you're correct or not.

You know that the information about whether the marble is bumpy or smooth changes the probability of what color it is, and you want some help with your guesses.

Write a function color_probability() that takes two arguments: a color ('red', 'yellow', or 'green') and a texture ('bumpy' or 'smooth') and returns the probability as a decimal fraction accurate to two places.

The probability should be a string and should discard any digits after the 100ths place. For example, 2 / 3 or 0.6666666666666666 would become the string '0.66'. Note this is different from rounding.

As a complete example, color_probability('red', 'bumpy') should return the string '0.57'.

In [39]:
def color_probability(color,texture):
    bag_prob = {'smooth red':0.33,'bumpy red':0.57,'bumpy yellow':0.28,'smooth yellow':0.33,'bumpy green':0.14,'smooth green':0.33}
    res = color + ' ' + texture
    prob = bag_prob[res]
    return prob

In [40]:
color_probability('smooth','red')

0.33